version: "3"
services:
  backend:
    build: ./backend
    environment:
      - PORT=3001
    deploy:
      replicas: 4
    networks:
      - loadbalancing

  nginx:
    build: ../nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  loadbalancing:

