apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gustavofdeoliveira/confluentinc-cp-enterprise-control-center:latest
          ports:
            - containerPort: 9021
          env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"
            - name: "PORT"
              value : 9021
           