name: CI/CD Backend

on:
  push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up Backend .env file
        working-directory: backend/
        run: make env
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build Docker images
        working-directory: backend/
        run: |
          make infra

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Show Docker Images
        run: docker images ls

      - name: ZOOKEEPER - Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/zookeeper:${{ github.sha }}

      - name: KAFKA - Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/kafka:${{ github.sha }}

      - name: REDIS - Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/redis:${{ github.sha }}

      - name: CONTROL CENTER - Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/control-center:${{ github.sha }}

      - name: POSTGRES - Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/postgres:${{ github.sha }}
  tag:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: ZOOKEEPER - Tag the Docker image with 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/zookeeper:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/zookeeper:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/zookeeper:latest

      - name: KAFKA - Tag the Docker image with 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/kafka:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/kafka:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/kafka:latest

      - name: REDIS - Tag the Docker image with 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/redis:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/redis:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/redis:latest

      - name: CONTROL CENTER - Tag the Docker image with 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/control-center:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/control-center:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/control-center:latest

      - name: POSTGRES - Tag the Docker image with 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/postgres:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/postgres:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres:latest
