name: CI/CD Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up Backend .env file
        working-directory: backend/
        run: make env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build Docker images
        working-directory: backend/
        run: |
          make infra

      - name: Show Docker Images after build
        run: docker images

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    #   - name: ZOOKEEPER - Push Docker image
    #     working-directory: backend/
    #     run: docker tag confluentinc/cp-zookeeper:latest ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-zookeeper:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-zookeeper:${{ github.sha }}

      - name: KAFKA - Push Docker image
        working-directory: backend/
        run: docker tag confluentinc/cp-kafka:latest ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-kafka:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-kafka:${{ github.sha }}

      - name: REDIS - Push Docker image
        working-directory: backend/
        run: docker tag redis:latest ${{ secrets.DOCKER_USERNAME }}/redis:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/redis:${{ github.sha }}

      - name: CONTROL CENTER - Push Docker image
        working-directory: backend/
        run: docker tag confluentinc/cp-enterprise-control-center:latest ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-enterprise-control-center:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-enterprise-control-center:${{ github.sha }}

      - name: POSTGRES - Push Docker image
        working-directory: backend/
        run: docker tag postgres:latest ${{ secrets.DOCKER_USERNAME }}/postgres:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/postgres:${{ github.sha }}
