name: CI/CD Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up Backend .env file
        working-directory: backend/
        run: make env

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build Docker images
        working-directory: backend/
        run: |
          make infra

      - name: Save Docker images to files
        run: |
          docker save confluentinc/cp-zookeeper:latest -o cp-zookeeper.tar
          docker save confluentinc/cp-kafka:latest -o cp-kafka.tar
          docker save redis:latest -o redis.tar
          docker save confluentinc/cp-enterprise-control-center:latest -o cp-enterprise-control-center.tar
          docker save postgres:latest -o postgres.tar

      - name: Upload Docker images as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docker-images
          path: |
            cp-zookeeper.tar
            cp-kafka.tar
            redis.tar
            cp-enterprise-control-center.tar
            postgres.tar

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker images artifacts
        uses: actions/download-artifact@v2
        with:
          name: docker-images

      - name: Load Docker images from files
        run: |
          docker load -i cp-zookeeper.tar
          docker load -i cp-kafka.tar
          docker load -i redis.tar
          docker load -i cp-enterprise-control-center.tar
          docker load -i postgres.tar

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Show Docker Images
        run: docker images

      - name: ZOOKEEPER - Push Docker image
        run: docker tag confluentinc/cp-zookeeper:latest ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-zookeeper:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-zookeeper:${{ github.sha }}

      - name: KAFKA - Push Docker image
        run: docker tag confluentinc/cp-kafka:latest ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-kafka:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-kafka:${{ github.sha }}

      - name: REDIS - Push Docker image
        run: docker tag redis:latest ${{ secrets.DOCKER_USERNAME }}/redis:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/redis:${{ github.sha }}

      - name: CONTROL CENTER - Push Docker image
        run: docker tag confluentinc/cp-enterprise-control-center:latest ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-enterprise-control-center:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/confluentinc/cp-enterprise-control-center:${{ github.sha }}

      - name: POSTGRES - Push Docker image
        run: docker tag postgres:latest ${{ secrets.DOCKER_USERNAME }}/postgres:${{ github.sha }} && docker push ${{ secrets.DOCKER_USERNAME }}/postgres:${{ github.sha }}
