name: CI/CD Backend

on:
  push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run make
        run: make

      - name: Set up Backend .env file
        working-directory: backend/
        run: make env
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build Docker images
        working-directory: backend/
        run: |
          make infra

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/my-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push $DOCKER_USERNAME/my-app:${{ github.sha }}

      - name: Tag the Docker image with 'latest'
        run: |
          docker tag $DOCKER_USERNAME/my-app:${{ github.sha }} $DOCKER_USERNAME/my-app:latest
          docker push $DOCKER_USERNAME/my-app:latest
